# Generated by Django 5.1.4 on 2024-12-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gst',
            field=models.IntegerField(default=True),
        ),
    ]
